packages:
  - 'apps/*'
  - 'packages/*'
  - 'workers/*'

overrides:
  csstype: 3.1.3
  '@types/react': 18.3.23
  '@types/react-dom': 18.3.7
  '@inkjs/ui>react': 19.2.4

peerDependencyRules:
  allowedVersions:
    'vocs>react': '18'
    'vocs>react-dom': '18'

allowBuilds:
  '@biomejs/biome': true
  '@reown/appkit': true
  '@tailwindcss/oxide': true
  bufferutil: true
  core-js-pure: true
  esbuild: true
  msw: true
  sharp: true
  utf-8-validate: true
  workerd: true
