import { GITHUB_URL } from "../config/constants";
import type { Schema } from "../types";

const CONTRACT_SCHEMA_VERSION = '2.0.0';

export const CONTRACT_SCHEMA: Schema = {
  $id: `${GITHUB_URL}/tree/main/packages/schemas/published/contract/versions/${CONTRACT_SCHEMA_VERSION}`,
  source: GITHUB_URL,
  title: 'Contract',
  version: CONTRACT_SCHEMA_VERSION,
  description: 'An on-chain smart contract found at this node\'s resolved address.',
  type: 'object' as const,
  properties: {
    class: {
      type: 'string',
      default: 'Contract',
      description: 'Class identifier for this node',
    },
    schema: {
      type: 'string',
      format: 'uri',
      description: 'URI pointing to the contract schema',
    },
    name: {
      type: 'string',
      description: 'Display name of the contract',
    },
    description: {
      type: 'string',
      description: 'Short description of the contract purpose',
    },
    avatar: {
      type: 'string',
      description: 'URI pointing to the contract\'s or owner\'s avatar',
    },
    category: {
      type: 'string',
      description: 'The category of the contract',
      examples: ['defi', 'gaming', 'dao', 'utility', 'proxy', 'factory'],
    },
    license: {
      type: 'string',
      description: 'Official software license identifier for the source code',
    },
    docs: {
      type: 'string',
      description: 'Primary documentation URL for developers and users',
      format: 'uri',
    },
    'compiled-metadata': {
      type: 'string',
      format: 'uri',
      description:
        'URI pointing to a contract metadata file as generated by a Solidity or Vyper compiler',
    },
    audits: {
      type: 'string',
      description: 'Third-party audit reports (URI or inline data',
    },
  },
  required: ['class', 'schema'],
  recommended: ['alias', 'description']
};
